---
# Clsuters to delete
clusters_delete:
  - name: "sample-cluster-name"
    uid: "sample-cluster-uid"

# Global delete configuration
delete_all_cluster_backups: false
delete_restores: false

        