---
# Clusters to inspect
clusters_inspect:
  - name: "cluster-1"
    include_secrets: false

  - name: "cluster-2"
    include_secrets: false

  - name: "cluster-3"
    include_secrets: false

# Global inspect configuration
default_include_secrets: false