---
# Clusters to update
backup_share_updates:
  - name: "px-source"
    add_backup_share:
      groups:
        - id: "group1"
          access: "FullAccess"
      collaborators:
        - id: "user2"
          access: "View"
    del_backup_share: {}
      # groups:
      #   - id: "group1"
      #     access: "FullAccess"
      # collaborators:
      #   - id: "user2"
      #     access: "View"
