---
# Backup locations to inspect
backup_locations_inspect:
  - name: "bl-1"
    include_secrets: false

  - name: "bl-2"
    include_secrets: false

  - name: "bl-3"
    include_secrets: false

# Global inspect configuration
default_include_secrets: false