---
# Backup locations to update
backup_ownership_updates:
  - name: "bl-1"
    ownership:
      owner: "9f2a1ab7-fee0"
      groups:
        - id: "test-grp-0"
          access: "Write"
      collaborators:
        - id: "95d5fd0d-2b95-4bfc"
          access: "Read"

  - name: "gcp-backup-2"
    ownership:
      owner: "9f2a1ab7-fee0"
      groups:
        - id: "test-grp-0"
          access: "Write"
      collaborators:
        - id: "95d5fd0d-2b95-4bfc"
          access: "Read"

  - name: "azure-backup-test-2"
    ownership:
      owner: "9f2a1ab7-fee0"
      groups:
        - id: "test-grp-0"
          access: "Write"
      collaborators:
        - id: "95d5fd0d-2b95-4bfc"
          access: "Read"

  - name: "nfs-backup-2"
    ownership:
      owner: "9f2a1ab7-fee0"
      groups:
        - id: "test-grp-0"
          access: "Write"
      collaborators:
        - id: "95d5fd0d-2b95-4bfc"
          access: "Read"
    


# Global update configuration
backup_configs: true