---
# Backup locations to validate
backup_locations_validate:
  - name: "bl-1"
    include_secrets: false

  - name: "bl-2"
    include_secrets: false
  
  - name: "bl-3"
    include_secrets: false
  
  - name: "bl-4"
    include_secrets: false
  
# Global inspect configuration
default_include_secrets: false