# ansible-collection/inventory/group_vars/volume_resource_only_policy/delete.yaml
---
# Define volume resource only policies to delete
volume_resource_only_policy_deletes:
  # Example: Delete portworx skip policy
  - name: "skip-portworx-policy"

  # Example: Delete CSI skip policy
  # - name: "skip-csi-policy"