# List of schedule_policies to update
schedule_policy_updates:
  - name: "test-policy-2"
    schedule_policy:
      interval:
        minutes: 15
        retain: 5 
        incremental_count:
          count: 5
    # Optional updates - only include fields you want to update
    labels:
      environment: "generic"
      team: "generic-team"