---
# Policies to update
schedule_policy_ownership_updates:
  - name: "test-policy-2"
    ownership:
      owner: "owner-name"
      groups:
        - id: "test-grp-0"
          access: "Write"
      collaborators:
        - id: "test-user-0"
          access: "Read"
