# ansible-collection/inventory/group_vars/backup/update.yaml
---
# List of backups to update
backup_updates:
  - name: "test-g-c1897a0-interval-2025-09-04-054335"  # Use the actual backup name
# Optional updates - only include fields you want to update
    labels:
      environment: "production"
      app: "mysql"
    # ownership:
    #   owner: "65b8227a-07b9-472f-b132-821af82b0de2"  # Use actual owner ID
    #   groups:
    #     - id: "platform-team"
    #       access: "Write"
    #   collaborators:
    #     - id: "user1@example.com"
    #       access: "Read"