---
# Rules to update
rule_ownership_updates:
  - name: "test-rule-1"
    ownership:
      owner: "owner-name"
      groups:
        - id: "test-grp-0"
          access: "Write"
      collaborators:
        - id: "test-user-0"
          access: "Read"
