---
# Roles to inspect
roles_inspect:
  - name: "test-role-from-ansible-auto"
    # role_id will be automatically determined from current user token

  - name: "test-role-from-ansible-specific"
    role_id: "603ded96-1c75-4320-ac03-d9046e563824"  # Specific user ID

  # - name: "another-dummy"
  #   role_id: "3fe6c733-6df6-4058-91b8-bcd3344c8564"
