---
# Define recipients configuration
recipients:
  - name: "dev-team"
    recipient_type: "EMAIL"
    recipient_ids:
      - "dev1@example.com"
      - "dev2@example.com"
    receiver_ref:
      name: "smtp"  # Name of your SMTP receiver
    active: true
