---
# Define recipients to update
recipients_to_update:
  - name: "recipient-uuid"  
    recipient_type: "EMAIL"
    recipient_ids:
      - "recipient1@example.com"
      - "recipient2@example.com"
      - "recipient3@example.com"  # Adding a new recipient
    receiver_ref:
      name: "smtp"
    severity: "CRITICAL" 
    active: true